import { Pack } from "@/types";

export const packs: Pack[] = [
  // Base Game
  { id: "bg", name: "Base Game", type: "bg", isOwned: true },

  // Expansion Packs (EP)
  { id: "ep01", name: "Get to Work", type: "ep", isOwned: true },
  { id: "ep02", name: "Get Together", type: "ep", isOwned: true },
  { id: "ep03", name: "City Living", type: "ep", isOwned: true },
  { id: "ep04", name: "Cats & Dogs", type: "ep", isOwned: true },
  { id: "ep05", name: "Seasons", type: "ep", isOwned: true },
  { id: "ep06", name: "Get Famous", type: "ep", isOwned: true },
  { id: "ep07", name: "Island Living", type: "ep", isOwned: true },
  { id: "ep08", name: "Discover University", type: "ep", isOwned: true },
  { id: "ep09", name: "Eco Lifestyle", type: "ep", isOwned: true },
  { id: "ep10", name: "Snowy Escape", type: "ep", isOwned: true },
  { id: "ep11", name: "Cottage Living", type: "ep", isOwned: true },
  { id: "ep12", name: "High School Years", type: "ep", isOwned: true },
  { id: "ep13", name: "Growing Together", type: "ep", isOwned: true },
  { id: "ep14", name: "Horse Ranch", type: "ep", isOwned: true },
  { id: "ep15", name: "For Rent", type: "ep", isOwned: true },
  { id: "ep16", name: "Lovestruck", type: "ep", isOwned: true },
  { id: "ep17", name: "Life & Death", type: "ep", isOwned: true },
  { id: "ep18", name: "Businesses & Hobbies", type: "ep", isOwned: true },
  { id: "ep19", name: "Enchanted by Nature", type: "ep", isOwned: false },

  // Game Packs (GP)
  { id: "gp01", name: "Outdoor Retreat", type: "gp", isOwned: true },
  { id: "gp02", name: "Spa Day", type: "gp", isOwned: true },
  { id: "gp03", name: "Dine Out", type: "gp", isOwned: true },
  { id: "gp04", name: "Vampires", type: "gp", isOwned: true },
  { id: "gp05", name: "Parenthood", type: "gp", isOwned: true },
  { id: "gp06", name: "Jungle Adventure", type: "gp", isOwned: true },
  { id: "gp07", name: "StrangerVille", type: "gp", isOwned: true },
  { id: "gp08", name: "Realm of Magic", type: "gp", isOwned: true },
  {
    id: "gp09",
    name: "Star Wars: Journey to Batuu",
    type: "gp",
    isOwned: true,
  },
  { id: "gp10", name: "Dream Home Decorator", type: "gp", isOwned: true },
  { id: "gp11", name: "My Wedding Stories", type: "gp", isOwned: true },
  { id: "gp12", name: "Werewolves", type: "gp", isOwned: true },

  // Stuff Packs (SP)
  { id: "sp01", name: "Luxury Party Stuff", type: "sp", isOwned: true },
  { id: "sp02", name: "Perfect Patio Stuff", type: "sp", isOwned: true },
  { id: "sp03", name: "Cool Kitchen Stuff", type: "sp", isOwned: true },
  { id: "sp04", name: "Spooky Stuff", type: "sp", isOwned: true },
  { id: "sp05", name: "Movie Hangout Stuff", type: "sp", isOwned: true },
  { id: "sp06", name: "Romantic Garden Stuff", type: "sp", isOwned: true },
  { id: "sp07", name: "Kids Room Stuff", type: "sp", isOwned: true },
  { id: "sp08", name: "Backyard Stuff", type: "sp", isOwned: true },
  { id: "sp09", name: "Vintage Glamour Stuff", type: "sp", isOwned: true },
  { id: "sp10", name: "Bowling Night Stuff", type: "sp", isOwned: true },
  { id: "sp11", name: "Fitness Stuff", type: "sp", isOwned: true },
  { id: "sp12", name: "Toddler Stuff", type: "sp", isOwned: true },
  { id: "sp13", name: "Laundry Day Stuff", type: "sp", isOwned: true },
  { id: "sp14", name: "My First Pet Stuff", type: "sp", isOwned: true },
  { id: "sp15", name: "Moschino Stuff", type: "sp", isOwned: true },
  { id: "sp16", name: "Tiny Living Stuff", type: "sp", isOwned: true },
  { id: "sp17", name: "Nifty Knitting Stuff", type: "sp", isOwned: true },
  { id: "sp18", name: "Paranormal Stuff", type: "sp", isOwned: true },
  { id: "sp19", name: "Home Chef Hustle Stuff", type: "sp", isOwned: true },
  { id: "sp20", name: "Crystal Creations Stuff", type: "sp", isOwned: true },

  // Kits (including Creator Kits)
  { id: "kit01", name: "Throwback Fit Kit", type: "kit", isOwned: true },
  { id: "kit02", name: "Country Kitchen Kit", type: "kit", isOwned: true },
  { id: "kit03", name: "Bust the Dust Kit", type: "kit", isOwned: false },
  { id: "kit04", name: "Courtyard Oasis Kit", type: "kit", isOwned: false },
  { id: "kit05", name: "Industrial Loft Kit", type: "kit", isOwned: true },
  { id: "kit06", name: "Fashion Street Kit", type: "kit", isOwned: false },
  { id: "kit07", name: "Incheon Arrivals Kit", type: "kit", isOwned: true },
  { id: "kit08", name: "Blooming Rooms Kit", type: "kit", isOwned: true },
  { id: "kit09", name: "Modern Menswear Kit", type: "kit", isOwned: false },
  { id: "kit10", name: "Carnaval Streetwear Kit", type: "kit", isOwned: false },
  { id: "kit11", name: "Décor to the Max Kit", type: "kit", isOwned: false },
  { id: "kit12", name: "Moonlight Chic Kit", type: "kit", isOwned: true },
  { id: "kit13", name: "Little Campers Kit", type: "kit", isOwned: true },
  { id: "kit14", name: "First Fits Kit", type: "kit", isOwned: false },
  { id: "kit15", name: "Desert Luxe Kit", type: "kit", isOwned: false },
  { id: "kit16", name: "Everyday Clutter Kit", type: "kit", isOwned: true },
  { id: "kit17", name: "Pastel Pop Kit", type: "kit", isOwned: false },
  { id: "kit18", name: "Bathroom Clutter Kit", type: "kit", isOwned: true },
  {
    id: "kit19",
    name: "Simtimates Collection Kit",
    type: "kit",
    isOwned: true,
  },
  { id: "kit20", name: "Basement Treasures Kit", type: "kit", isOwned: true },
  { id: "kit21", name: "Greenhouse Haven Kit", type: "kit", isOwned: false },
  { id: "kit22", name: "Grunge Revival Kit", type: "kit", isOwned: true },
  { id: "kit23", name: "Book Nook Kit", type: "kit", isOwned: false },
  { id: "kit24", name: "Poolside Splash Kit", type: "kit", isOwned: false },
  { id: "kit25", name: "Modern Luxe Kit", type: "kit", isOwned: false },
  { id: "kit26", name: "Goth Galore Kit", type: "kit", isOwned: true },
  { id: "kit27", name: "Castle Estate Kit", type: "kit", isOwned: false },
  { id: "kit28", name: "Party Essentials Kit", type: "kit", isOwned: false },
  { id: "kit29", name: "Urban Homage Kit", type: "kit", isOwned: false },
  { id: "kit30", name: "Riviera Retreat Kit", type: "kit", isOwned: false },
  { id: "kit31", name: "Cozy Bistro Kit", type: "kit", isOwned: true },
  { id: "kit32", name: "Artist Studio Kit", type: "kit", isOwned: false },
  { id: "kit33", name: "Storybook Nursery Kit", type: "kit", isOwned: true },
  { id: "kit34", name: "Sweet Slumber Party Kit", type: "kit", isOwned: false },
  { id: "kit35", name: "Cozy Kitsch Kit", type: "kit", isOwned: false },
  { id: "kit36", name: "Comfy Gamer Kit", type: "kit", isOwned: false },
  { id: "kit37", name: "Secret Sanctuary Kit", type: "kit", isOwned: false },
  { id: "kit38", name: "Casanova Cave Kit", type: "kit", isOwned: true },
  { id: "kit39", name: "Refined Living Room Kit", type: "kit", isOwned: false },
  { id: "kit40", name: "Business Chic Kit", type: "kit", isOwned: true },
  { id: "kit41", name: "Sleek Bathroom Kit", type: "kit", isOwned: false },
  { id: "kit42", name: "Sweet Allure Kit", type: "kit", isOwned: false },
  { id: "kit43", name: "Kitchen Clutter Kit", type: "kit", isOwned: true },
  { id: "kit44", name: "Golden Years Kit", type: "kit", isOwned: true },
  { id: "kit45", name: "Restoration Workshop Kit", type: "kit", isOwned: true },
];
