import { Sim } from "@/types";

export const sims: Sim[] = [
  {
    id: "summer_holiday",
    name: "Summer Holiday",
    householdId: "bff",
    marked: false,
  },
  {
    id: "travis_scott",
    name: "Travis Scott",
    householdId: "bff",
    marked: false,
  },
  { id: "liberty_lee", name: "Liberty Lee", householdId: "bff", marked: false },
  {
    id: "bob_pancakes",
    name: "Bob Pancakes",
    householdId: "pancakes",
    marked: false,
  },
  {
    id: "eliza_pancakes",
    name: "Eliza Pancakes",
    householdId: "pancakes",
    marked: false,
  },
  {
    id: "alice_spencer_kim",
    name: "Alice Spencer-Kim",
    householdId: "spencer_kim_lewis",
    marked: false,
  },
  {
    id: "dennis_kim",
    name: "Dennis Kim",
    householdId: "spencer_kim_lewis",
    marked: false,
  },
  {
    id: "olivia_kim_lewis",
    name: "Olivia Kim-Lewis",
    householdId: "spencer_kim_lewis",
    marked: false,
  },
  {
    id: "eric_lewis",
    name: "Eric Lewis",
    householdId: "spencer_kim_lewis",
    marked: false,
  },
  {
    id: "vivian_lewis",
    name: "Vivian Lewis",
    householdId: "spencer_kim_lewis",
    marked: false,
  },
  {
    id: "mortimer_goth",
    name: "Mortimer Goth",
    householdId: "goth",
    marked: false,
  },
  { id: "bella_goth", name: "Bella Goth", householdId: "goth", marked: false },
  {
    id: "cassandra_goth",
    name: "Cassandra Goth",
    householdId: "goth",
    marked: false,
  },
  {
    id: "alexander_goth",
    name: "Alexander Goth",
    householdId: "goth",
    marked: false,
  },
  {
    id: "johnny_zest",
    name: "Johnny Zest",
    householdId: "zest",
    marked: false,
  },
  {
    id: "j_huntington_iii",
    name: "J Huntington III",
    householdId: "roomies",
    marked: false,
  },
  {
    id: "mitchell_kalani",
    name: "Mitchell Kalani",
    householdId: "roomies",
    marked: false,
  },
  {
    id: "gavin_richards",
    name: "Gavin Richards",
    householdId: "roomies",
    marked: false,
  },
  { id: "zoe_patel", name: "Zoe Patel", householdId: "roomies", marked: false },
  {
    id: "katrina_caliente",
    name: "Katrina Caliente",
    householdId: "caliente",
    marked: false,
  },
  {
    id: "don_lothario",
    name: "Don Lothario",
    householdId: "caliente",
    marked: false,
  },
  {
    id: "nina_caliente",
    name: "Nina Caliente",
    householdId: "caliente",
    marked: false,
  },
  {
    id: "dina_caliente",
    name: "Dina Caliente",
    householdId: "caliente",
    marked: false,
  },
  {
    id: "geoffrey_landgraab",
    name: "Geoffrey Landgraab",
    householdId: "landgraab",
    marked: false,
  },
  {
    id: "nancy_landgraab",
    name: "Nancy Landgraab",
    householdId: "landgraab",
    marked: false,
  },
  {
    id: "malcolm_landgraab",
    name: "Malcolm Landgraab",
    householdId: "landgraab",
    marked: false,
  },
  { id: "candy_behr", name: "Candy Behr", householdId: "behr", marked: false },
  { id: "yuki_behr", name: "Yuki Behr", householdId: "behr", marked: false },
  {
    id: "clara_bjergsen",
    name: "Clara Bjergsen",
    householdId: "bjergsen",
    marked: false,
  },
  {
    id: "bjorn_bjergsen",
    name: "Bjorn Bjergsen",
    householdId: "bjergsen",
    marked: false,
  },
  {
    id: "sofia_bjergsen",
    name: "Sofia Bjergsen",
    householdId: "bjergsen",
    marked: false,
  },
  {
    id: "elsa_bjergsen",
    name: "Elsa Bjergsen",
    householdId: "bjergsen",
    marked: false,
  },
  {
    id: "sergio_romeo",
    name: "Sergio Romeo",
    householdId: "bro",
    marked: false,
  },
  {
    id: "joaquin_le_chien",
    name: "Joaquin Le Chien",
    householdId: "bro",
    marked: false,
  },
  {
    id: "ulrike_faust",
    name: "Ulrike Faust",
    householdId: "free_spirits",
    marked: false,
  },
  {
    id: "maaike_haas",
    name: "Maaike Haas",
    householdId: "free_spirits",
    marked: false,
  },
  {
    id: "moira_fyres",
    name: "Moira Fyres",
    householdId: "fyres",
    marked: false,
  },
  {
    id: "dominic_fyres",
    name: "Dominic Fyres",
    householdId: "fyres",
    marked: false,
  },
  {
    id: "siobhan_fyres",
    name: "Siobhan Fyres",
    householdId: "fyres",
    marked: false,
  },
  {
    id: "morgan_fyres",
    name: "Morgan Fyres",
    householdId: "fyres",
    marked: false,
  },
  { id: "mila_munch", name: "Mila Munch", householdId: "munch", marked: false },
  {
    id: "gunther_munch",
    name: "Gunther Munch",
    householdId: "munch",
    marked: false,
  },
  {
    id: "wolfgang_munch",
    name: "Wolfgang Munch",
    householdId: "munch",
    marked: false,
  },
  {
    id: "lucas_munch",
    name: "Lucas Munch",
    householdId: "munch",
    marked: false,
  },
  {
    id: "marcus_flex",
    name: "Marcus Flex",
    householdId: "partihaus",
    marked: false,
  },
  {
    id: "paolo_rocca",
    name: "Paolo Rocca",
    householdId: "partihaus",
    marked: false,
  },
  {
    id: "jade_rosa",
    name: "Jade Rosa",
    householdId: "partihaus",
    marked: false,
  },
  {
    id: "eva_capricciosa",
    name: "Eva Capricciosa",
    householdId: "partihaus",
    marked: false,
  },
  {
    id: "jacques_villareal",
    name: "Jacques Villareal",
    householdId: "villareal",
    marked: false,
  },
  {
    id: "luna_villareal",
    name: "Luna Villareal",
    householdId: "villareal",
    marked: false,
  },
  {
    id: "hugo_villareal",
    name: "Hugo Villareal",
    householdId: "villareal",
    marked: false,
  },
  {
    id: "max_villareal",
    name: "Max Villareal",
    householdId: "villareal",
    marked: false,
  },
  {
    id: "salim_benali",
    name: "Salim Benali",
    householdId: "benali",
    marked: false,
  },
  {
    id: "jesminder_bheeda",
    name: "Jesminder Bheeda",
    householdId: "bheeda",
    marked: false,
  },
  {
    id: "arun_bheeda",
    name: "Arun Bheeda",
    householdId: "bheeda",
    marked: false,
  },
  {
    id: "victor_feng",
    name: "Victor Feng",
    householdId: "feng",
    marked: false,
  },
  { id: "lily_feng", name: "Lily Feng", householdId: "feng", marked: false },
  { id: "baako_jang", name: "Baako Jang", householdId: "jang", marked: false },
  { id: "anaya_jang", name: "Anaya Jang", householdId: "jang", marked: false },
  {
    id: "billie_jang",
    name: "Billie Jang",
    householdId: "jang",
    marked: false,
  },
  {
    id: "miko_ojo",
    name: "Miko Ojo",
    householdId: "karaoke_legends",
    marked: false,
  },
  {
    id: "akira_kibo",
    name: "Akira Kibo",
    householdId: "karaoke_legends",
    marked: false,
  },
  {
    id: "darling_walsh",
    name: "Darling Walsh",
    householdId: "karaoke_legends",
    marked: false,
  },
  { id: "diego_lobo", name: "Diego Lobo", householdId: "lobo", marked: false },
  {
    id: "penny_pizzazz",
    name: "Penny Pizzazz",
    householdId: "pizzazz",
    marked: false,
  },
  {
    id: "geeta_rasoya",
    name: "Geeta Rasoya",
    householdId: "rasoya",
    marked: false,
  },
  {
    id: "raj_rasoya",
    name: "Raj Rasoya",
    householdId: "rasoya",
    marked: false,
  },
  {
    id: "vladislaus_straud",
    name: "Vladislaus Straud",
    householdId: "straud",
    marked: false,
  },
  {
    id: "caleb_vatore",
    name: "Caleb Vatore",
    householdId: "vatore",
    marked: false,
  },
  {
    id: "lilith_vatore",
    name: "Lilith Vatore",
    householdId: "vatore",
    marked: false,
  },
  {
    id: "brent_hecking",
    name: "Brent Hecking",
    householdId: "hecking",
    marked: false,
  },
  {
    id: "brant_hecking",
    name: "Brant Hecking",
    householdId: "hecking",
    marked: false,
  },
  {
    id: "catarina_lynx",
    name: "Catarina Lynx",
    householdId: "lynx",
    marked: false,
  },
  {
    id: "supriya_delgato",
    name: "Supriya Delgato",
    householdId: "delgato",
    marked: false,
  },
  {
    id: "justin_delgato",
    name: "Justin Delgato",
    householdId: "delgato",
    marked: false,
  },
  {
    id: "pierce_delgato",
    name: "Pierce Delgato",
    householdId: "delgato",
    marked: false,
  },
  {
    id: "evie_delgato",
    name: "Evie Delgato",
    householdId: "delgato",
    marked: false,
  },
  {
    id: "venessa_jeong",
    name: "Venessa Jeong",
    householdId: "jeong",
    marked: false,
  },
  {
    id: "octavia_moon",
    name: "Octavia Moon",
    householdId: "bailey_moon",
    marked: false,
  },
  {
    id: "thorne_bailey",
    name: "Thorne Bailey",
    householdId: "bailey_moon",
    marked: false,
  },
  {
    id: "orange_bailey_moon",
    name: "Orange Bailey-Moon",
    householdId: "bailey_moon",
    marked: false,
  },
  {
    id: "judith_ward",
    name: "Judith Ward",
    householdId: "ward",
    marked: false,
  },
  { id: "holly_alto", name: "Holly Alto", householdId: "alto", marked: false },
  {
    id: "baby_ariel",
    name: "Baby Ariel",
    householdId: "baby_ariel",
    marked: false,
  },
  {
    id: "dustin_broke",
    name: "Dustin Broke",
    householdId: "broke",
    marked: false,
  },
  { id: "brytani_cho", name: "Brytani Cho", householdId: "cho", marked: false },
  {
    id: "dirk_dreamer",
    name: "Dirk Dreamer",
    householdId: "dreamer",
    marked: false,
  },
  {
    id: "izzy_fabulous",
    name: "Izzy Fabulous",
    householdId: "fabulous",
    marked: false,
  },
  {
    id: "kayla_flemming",
    name: "Kayla Flemming",
    householdId: "flemming",
    marked: false,
  },
  {
    id: "jess_sigworth",
    name: "Jess Sigworth",
    householdId: "sigworth",
    marked: false,
  },
  {
    id: "dylan_sigworth",
    name: "Dylan Sigworth",
    householdId: "sigworth",
    marked: false,
  },
  {
    id: "christie_sigworth",
    name: "Christie Sigworth",
    householdId: "sigworth",
    marked: false,
  },
  {
    id: "george_cahill",
    name: "George Cahill",
    householdId: "cahill",
    marked: false,
  },
  {
    id: "ted_roswell",
    name: "Ted Roswell",
    householdId: "roswell",
    marked: false,
  },
  {
    id: "meredith_roswell",
    name: "Meredith Roswell",
    householdId: "roswell",
    marked: false,
  },
  {
    id: "alice_martin",
    name: "Alice Martin",
    householdId: "eclectic_arts",
    marked: false,
  },
  {
    id: "mark_eggleston",
    name: "Mark Eggleston",
    householdId: "eclectic_arts",
    marked: false,
  },
  {
    id: "leslie_holland",
    name: "Leslie Holland",
    householdId: "eclectic_arts",
    marked: false,
  },
  {
    id: "mele_kahananui",
    name: "Mele Kahananui",
    householdId: "kahananui",
    marked: false,
  },
  {
    id: "alika_kahananui",
    name: "Alika Kahananui",
    householdId: "kahananui",
    marked: false,
  },
  {
    id: "oliana_ngata",
    name: "Oliana Ngata",
    householdId: "ngata",
    marked: false,
  },
  { id: "tane_ngata", name: "Tane Ngata", householdId: "ngata", marked: false },
  {
    id: "leila_illes",
    name: "Leila Illes",
    householdId: "ngata",
    marked: false,
  },
  {
    id: "keala_hoapili",
    name: "Keala Hoapili",
    householdId: "hoapili",
    marked: false,
  },
  {
    id: "lia_hauata",
    name: "Lia Hauata",
    householdId: "hoapili",
    marked: false,
  },
  {
    id: "makoa_kealoha",
    name: "Makoa Kealoha",
    householdId: "kealoha",
    marked: false,
  },
  {
    id: "lilliana_kealoha",
    name: "Lilliana Kealoha",
    householdId: "kealoha",
    marked: false,
  },
  {
    id: "nani_kealoha",
    name: "Nani Kealoha",
    householdId: "kealoha",
    marked: false,
  },
  {
    id: "duane_talla",
    name: "Duane Talla",
    householdId: "kealoha",
    marked: false,
  },
  {
    id: "kalamainuu_iona",
    name: "Kalamainu'u Iona",
    householdId: "iona",
    marked: false,
  },
  {
    id: "nalani_mahi_ai",
    name: "Nalani Mahi'ai",
    householdId: "mahi_ai",
    marked: false,
  },
  { id: "pakaa_uha", name: "Paka'a Uha", householdId: "uha", marked: false },
  {
    id: "ukupanipo_hekekia",
    name: "Ukupanipo Hekekia",
    householdId: "hekekia",
    marked: false,
  },
  {
    id: "cameron_fletcher",
    name: "Cameron Fletcher",
    householdId: "fletcher",
    marked: false,
  },
  {
    id: "ekram_elderberry",
    name: "Ekram Elderberry",
    householdId: "elderberry",
    marked: false,
  },
  {
    id: "eleanore_elderberry",
    name: "Eleanore Elderberry",
    householdId: "elderberry",
    marked: false,
  },
  {
    id: "rohan_elderberry",
    name: "Rohan Elderberry",
    householdId: "elderberry",
    marked: false,
  },
  {
    id: "julia_wright",
    name: "Julia Wright",
    householdId: "best_of_friends",
    marked: false,
  },
  {
    id: "becca_clarke",
    name: "Becca Clarke",
    householdId: "best_of_friends",
    marked: false,
  },
  {
    id: "lilith_pleasant",
    name: "Lilith Pleasant",
    householdId: "pleasant",
    marked: false,
  },
  {
    id: "angela_pleasant",
    name: "Angela Pleasant",
    householdId: "pleasant",
    marked: false,
  },
  { id: "jing_fen", name: "Jing Fen", householdId: "fen", marked: false },
  {
    id: "lana_mckinnon",
    name: "Lana McKinnon",
    householdId: "mckinnon",
    marked: false,
  },
  {
    id: "serena_bhamra",
    name: "Serena Bhamra",
    householdId: "bhamra",
    marked: false,
  },
  {
    id: "thomas_jabari",
    name: "Thomas Jabari",
    householdId: "jabari",
    marked: false,
  },
  {
    id: "knox_greenburg",
    name: "Knox Greenburg",
    householdId: "greenburg",
    marked: false,
  },
  {
    id: "mary_greenburg",
    name: "Mary Greenburg",
    householdId: "greenburg",
    marked: false,
  },
  {
    id: "blossom_greenburg",
    name: "Blossom Greenburg",
    householdId: "greenburg",
    marked: false,
  },
  {
    id: "cletus_harris",
    name: "Cletus Harris",
    householdId: "harris",
    marked: false,
  },
  {
    id: "faye_harris",
    name: "Faye Harris",
    householdId: "harris",
    marked: false,
  },
  {
    id: "jeb_harris",
    name: "Jeb Harris",
    householdId: "harris",
    marked: false,
  },
  {
    id: "gideon_harris",
    name: "Gideon Harris",
    householdId: "harris",
    marked: false,
  },
  {
    id: "francine_spencer",
    name: "Francine Spencer",
    householdId: "harris",
    marked: false,
  },
  {
    id: "bess_sterling",
    name: "Bess Sterling",
    householdId: "sterling_rico",
    marked: false,
  },
  {
    id: "jules_rico",
    name: "Jules Rico",
    householdId: "sterling_rico",
    marked: false,
  },
  {
    id: "yasemin_tinker",
    name: "Yasemin Tinker",
    householdId: "tinker",
    marked: false,
  },
  {
    id: "tina_tinker",
    name: "Tina Tinker",
    householdId: "tinker",
    marked: false,
  },
  {
    id: "olive_tinker",
    name: "Olive Tinker",
    householdId: "tinker",
    marked: false,
  },
  {
    id: "jenna_akiyama",
    name: "Jenna Akiyama",
    householdId: "akiyama",
    marked: false,
  },
  {
    id: "kado_akiyama",
    name: "Kado Akiyama",
    householdId: "akiyama",
    marked: false,
  },
  {
    id: "taku_akiyama",
    name: "Taku Akiyama",
    householdId: "akiyama",
    marked: false,
  },
  {
    id: "miki_akiyama",
    name: "Miki Akiyama",
    householdId: "akiyama",
    marked: false,
  },
  { id: "naoki_ito", name: "Naoki Ito", householdId: "ito", marked: false },
  { id: "megumi_ito", name: "Megumi Ito", householdId: "ito", marked: false },
  { id: "kiyoshi_ito", name: "Kiyoshi Ito", householdId: "ito", marked: false },
  { id: "nanami_ito", name: "Nanami Ito", householdId: "ito", marked: false },
  {
    id: "shigeru_nishidake",
    name: "Shigeru Nishidake",
    householdId: "nishidake",
    marked: false,
  },
  {
    id: "sachiko_nishidake",
    name: "Sachiko Nishidake",
    householdId: "nishidake",
    marked: false,
  },
  {
    id: "kaori_nishidake",
    name: "Kaori Nishidake",
    householdId: "nishidake",
    marked: false,
  },
  {
    id: "cecilia_kang",
    name: "Cecilia Kang",
    householdId: "a_new_start",
    marked: false,
  },
  {
    id: "derek_mcmillan",
    name: "Derek McMillan",
    householdId: "moody_mcmillan",
    marked: false,
  },
  {
    id: "ian_moody",
    name: "Ian Moody",
    householdId: "moody_mcmillan",
    marked: false,
  },
  {
    id: "simon_scott",
    name: "Simon Scott",
    householdId: "scott",
    marked: false,
  },
  { id: "sara_scott", name: "Sara Scott", householdId: "scott", marked: false },
  {
    id: "thomas_watson",
    name: "Thomas Watson",
    householdId: "watson",
    marked: false,
  },
  {
    id: "rahmi_watson",
    name: "Rahmi Watson",
    householdId: "watson",
    marked: false,
  },
  {
    id: "rashidah_watson",
    name: "Rashidah Watson",
    householdId: "watson",
    marked: false,
  },
  {
    id: "imran_watson",
    name: "Imran Watson",
    householdId: "watson",
    marked: false,
  },
  {
    id: "maira_watson",
    name: "Maira Watson",
    householdId: "watson",
    marked: false,
  },
  {
    id: "lavina_chopra",
    name: "Lavina Chopra",
    householdId: "chopra",
    marked: false,
  },
  {
    id: "rahul_chopra",
    name: "Rahul Chopra",
    householdId: "chopra",
    marked: false,
  },
  {
    id: "arnessa_thebe",
    name: "Arnessa Thebe",
    householdId: "laurent",
    marked: false,
  },
  {
    id: "hector_laurent",
    name: "Hector Laurent",
    householdId: "laurent",
    marked: false,
  },
  {
    id: "hilary_laurent",
    name: "Hilary Laurent",
    householdId: "laurent",
    marked: false,
  },
  {
    id: "greta_laurent",
    name: "Greta Laurent",
    householdId: "laurent",
    marked: false,
  },
  {
    id: "jace_laurent",
    name: "Jace Laurent",
    householdId: "laurent",
    marked: false,
  },
  {
    id: "lucia_markovic",
    name: "Lucia Markovic",
    householdId: "markovic",
    marked: false,
  },
  {
    id: "mateo_markovic",
    name: "Mateo Markovic",
    householdId: "markovic",
    marked: false,
  },
  {
    id: "tomi_markovic",
    name: "Tomi Markovic",
    householdId: "markovic",
    marked: false,
  },
  {
    id: "camille_soto",
    name: "Camille Soto",
    householdId: "soto",
    marked: false,
  },
  {
    id: "dominique_soto",
    name: "Dominique Soto",
    householdId: "soto",
    marked: false,
  },
  {
    id: "faiz_jaleel",
    name: "Faiz Jaleel",
    householdId: "jaleel",
    marked: false,
  },
  {
    id: "kristopher_volkov",
    name: "Kristopher Volkov",
    householdId: "volkov",
    marked: false,
  },
  {
    id: "jacob_volkov",
    name: "Jacob Volkov",
    householdId: "volkov",
    marked: false,
  },
  { id: "lily_zhu", name: "Lily Zhu", householdId: "volkov", marked: false },
  {
    id: "lou_howell",
    name: "Lou Howell",
    householdId: "howell",
    marked: false,
  },
  {
    id: "rory_oaklow",
    name: "Rory Oaklow",
    householdId: "oaklow",
    marked: false,
  },
  {
    id: "celene_lopez",
    name: "Celene López",
    householdId: "celene_lopez",
    marked: false,
  },
  {
    id: "wolfgang_wilder",
    name: "Wolfgang Wilder",
    householdId: "wilder",
    marked: false,
  },
  { id: "ava_harjo", name: "Ava Harjo", householdId: "harjo", marked: false },
  {
    id: "lucha_harjo",
    name: "Lucha Harjo",
    householdId: "harjo",
    marked: false,
  },
  { id: "noah_kane", name: "Noah Kane", householdId: "harjo", marked: false },
  { id: "ash_harjo", name: "Ash Harjo", householdId: "harjo", marked: false },
  { id: "tai_lum", name: "Tai Lum", householdId: "prescott", marked: false },
  {
    id: "mei_prescott",
    name: "Mei Prescott",
    householdId: "prescott",
    marked: false,
  },
  {
    id: "molly_prescott",
    name: "Molly Prescott",
    householdId: "prescott",
    marked: false,
  },
  {
    id: "amy_prescott",
    name: "Amy Prescott",
    householdId: "prescott",
    marked: false,
  },
  {
    id: "marcel_price",
    name: "Marcel Price",
    householdId: "price",
    marked: false,
  },
  {
    id: "janae_price",
    name: "Janae Price",
    householdId: "price",
    marked: false,
  },
  { id: "kevin_puri", name: "Kevin Puri", householdId: "price", marked: false },
  {
    id: "sidney_price",
    name: "Sidney Price",
    householdId: "price",
    marked: false,
  },
  {
    id: "savannah_price",
    name: "Savannah Price",
    householdId: "price",
    marked: false,
  },
  {
    id: "jayden_price",
    name: "Jayden Price",
    householdId: "price",
    marked: false,
  },
  {
    id: "eloise_hiddlestix",
    name: "Eloise Hiddlestix",
    householdId: "hiddlestix",
    marked: false,
  },
  {
    id: "rita_coombes",
    name: "Rita Coombes",
    householdId: "coombes",
    marked: false,
  },
  {
    id: "anjelo_morlind",
    name: "Anjelo Morlind",
    householdId: "morlind",
    marked: false,
  },
  {
    id: "celeste_michaelson",
    name: "Celeste Michaelson",
    householdId: "michaelson",
    marked: false,
  },
  {
    id: "christopher_michaelson",
    name: "Christopher Michaelson",
    householdId: "michaelson",
    marked: false,
  },
  {
    id: "atlas_michaelson",
    name: "Atlas Michaelson",
    householdId: "michaelson",
    marked: false,
  },
  {
    id: "orion_michaelson",
    name: "Orion Michaelson",
    householdId: "michaelson",
    marked: false,
  },
  {
    id: "ignacio_robles",
    name: "Ignacio Robles",
    householdId: "robles",
    marked: false,
  },
  {
    id: "bernice_robles",
    name: "Bernice Robles",
    householdId: "robles",
    marked: false,
  },
  {
    id: "ian_robles",
    name: "Ian Robles",
    householdId: "robles",
    marked: false,
  },
  {
    id: "aurelio_robles",
    name: "Aurelio Robles",
    householdId: "robles",
    marked: false,
  },

  {
    id: "jay_robles",
    name: "Jay Robles",
    householdId: "robles_ruano",
    marked: false,
  },
  {
    id: "doli_ruano",
    name: "Doli Ruano",
    householdId: "robles_ruano",
    marked: false,
  },
  {
    id: "tala_ruano",
    name: "Tala Ruano",
    householdId: "robles_ruano",
    marked: false,
  },
  {
    id: "xochitl_luna",
    name: "Xochitl Luna",
    householdId: "luna_sullivan",
    marked: false,
  },
  {
    id: "karmine_luna",
    name: "Karmine Luna",
    householdId: "luna_sullivan",
    marked: false,
  },
  {
    id: "eleanor_sullivan",
    name: "Eleanor Sullivan",
    householdId: "luna_sullivan",
    marked: false,
  },
  {
    id: "kyle_kyleson",
    name: "Kyle Kyleson",
    householdId: "kyleson",
    marked: false,
  },
  {
    id: "don_gooseman",
    name: "Don Gooseman",
    householdId: "gooseman",
    marked: false,
  },
  {
    id: "marissa_tracey",
    name: "Marissa Tracey",
    householdId: "nectar_making_duo",
    marked: false,
  },
  {
    id: "dani_davila",
    name: "Dani Davila",
    householdId: "nectar_making_duo",
    marked: false,
  },
  {
    id: "umber_grove",
    name: "Umber Grove",
    householdId: "grove",
    marked: false,
  },
  {
    id: "juniper_grove",
    name: "Juniper Grove",
    householdId: "grove",
    marked: false,
  },
  { id: "wren_grove", name: "Wren Grove", householdId: "grove", marked: false },
  {
    id: "sienna_grove",
    name: "Sienna Grove",
    householdId: "sienna_flapjack",
    marked: false,
  },
  {
    id: "vanesha_cahyaputri",
    name: "Vanesha Cahyaputri",
    householdId: "cahyaputri",
    marked: false,
  },
  {
    id: "zhafira_cahyaputri",
    name: "Zhafira Cahyaputri",
    householdId: "cahyaputri",
    marked: false,
  },
  {
    id: "chanh_linh",
    name: "Chánh Linh",
    householdId: "linh_sadya",
    marked: false,
  },
  {
    id: "arturo_linh",
    name: "Arturo Linh",
    householdId: "linh_sadya",
    marked: false,
  },
  {
    id: "lien_sadya",
    name: "Liên Sadya",
    householdId: "linh_sadya",
    marked: false,
  },
  {
    id: "alon_sadya",
    name: "Alon Sadya",
    householdId: "linh_sadya",
    marked: false,
  },
  {
    id: "cam_sadya",
    name: "Cam Sadya",
    householdId: "linh_sadya",
    marked: false,
  },
  { id: "thi_linh", name: "Thi Linh", householdId: "linh", marked: false },
  {
    id: "bua_bun_ma",
    name: "Bua Bun Ma",
    householdId: "bun_ma",
    marked: false,
  },
  {
    id: "kasem_bun_ma",
    name: "Kasem Bun Ma",
    householdId: "bun_ma",
    marked: false,
  },
  {
    id: "nin_bun_ma",
    name: "Nin Bun Ma",
    householdId: "bun_ma",
    marked: false,
  },
  {
    id: "sud_bun_ma",
    name: "Sud Bun Ma",
    householdId: "bun_ma",
    marked: false,
  },
  { id: "panya_li", name: "Panya Li", householdId: "panya_li", marked: false },
  { id: "aziz_nadir", name: "Aziz Nadir", householdId: "nadir", marked: false },
  {
    id: "valentina_nadir",
    name: "Valentina Nadir",
    householdId: "nadir",
    marked: false,
  },
  {
    id: "manuel_aguilar",
    name: "Manuel Aguilar",
    householdId: "dynamic_daters",
    marked: false,
  },
  {
    id: "carmen_ortega",
    name: "Carmen Ortega",
    householdId: "dynamic_daters",
    marked: false,
  },
  {
    id: "elia_cruz",
    name: "Elia Cruz",
    householdId: "dynamic_daters",
    marked: false,
  },
  {
    id: "yoltic_xicotencatl",
    name: "Yoltic Xicoténcatl",
    householdId: "dynamic_daters",
    marked: false,
  },
  {
    id: "monica_lopez",
    name: "Mónica López",
    householdId: "lopez",
    marked: false,
  },
  {
    id: "carlos_lopez",
    name: "Carlos López",
    householdId: "lopez",
    marked: false,
  },
  { id: "luz_lopez", name: "Luz López", householdId: "lopez", marked: false },
  {
    id: "esther_gomes",
    name: "Esther Gomes",
    householdId: "izadi_gomes",
    marked: false,
  },
  {
    id: "zuleika_izadi",
    name: "Zuleika Izadi",
    householdId: "izadi_gomes",
    marked: false,
  },
  {
    id: "tziporah_gomes",
    name: "Tziporah Gomes",
    householdId: "gomes",
    marked: false,
  },
  {
    id: "radwan_gomes",
    name: "Radwan Gomes",
    householdId: "gomes",
    marked: false,
  },
  {
    id: "zelmira_gomes",
    name: "Zelmira Gomes",
    householdId: "gomes",
    marked: false,
  },
  {
    id: "kai_aether",
    name: "Kai Aether",
    householdId: "aether",
    marked: false,
  },
  {
    id: "ekade_aether",
    name: "Ekade Aether",
    householdId: "aether",
    marked: false,
  },
  {
    id: "takama_aether",
    name: "Takama Aether",
    householdId: "aether",
    marked: false,
  },
  {
    id: "olive_specter",
    name: "Olive Specter",
    householdId: "specter",
    marked: false,
  },
  {
    id: "nyon_specter",
    name: "Nyon Specter",
    householdId: "specter",
    marked: false,
  },
  {
    id: "layne_coffin",
    name: "Layne Coffin",
    householdId: "specter",
    marked: false,
  },
  {
    id: "gert_koopman",
    name: "Gert Koopman",
    householdId: "koopman",
    marked: false,
  },
  {
    id: "jolanda_koopman",
    name: "Jolanda Koopman",
    householdId: "koopman",
    marked: false,
  },
  {
    id: "cannonball_coleman",
    name: "Cannonball Coleman",
    householdId: "urbane_housesharers",
    marked: false,
  },
  {
    id: "crispin_black",
    name: "Crispin Black",
    householdId: "urbane_housesharers",
    marked: false,
  },
  {
    id: "ollie_mark",
    name: "Ollie Mark",
    householdId: "urbane_housesharers",
    marked: false,
  },
  {
    id: "nia_sarpong",
    name: "Nia Sarpong",
    householdId: "sarpong",
    marked: false,
  },
  {
    id: "lerato_sarpong",
    name: "Lerato Sarpong",
    householdId: "sarpong",
    marked: false,
  },
  {
    id: "hattie_loden",
    name: "Gramma Hattie Loden",
    householdId: "loden",
    marked: false,
  },
  {
    id: "dahlia_loden",
    name: "Dahlia Loden",
    householdId: "loden",
    marked: false,
  },
  { id: "nora_loden", name: "Nora Loden", householdId: "loden", marked: false },
  {
    id: "freya_loden",
    name: "Freya Loden",
    householdId: "loden",
    marked: false,
  },
  { id: "erik_loden", name: "Erik Loden", householdId: "loden", marked: false },
  {
    id: "bruno_hoffman",
    name: "Bruno Hoffman",
    householdId: "hoffman",
    marked: false,
  },
  {
    id: "felix_hoffman",
    name: "Felix Hoffman",
    householdId: "hoffman",
    marked: false,
  },
  {
    id: "corey_nyhus",
    name: "Corey Nyhus",
    householdId: "nyhus",
    marked: false,
  },
  { id: "zain_amri", name: "Zain Amri", householdId: "amri", marked: false },
  {
    id: "nadya_kishka",
    name: "Nadya Kishka",
    householdId: "mystical_besties",
    marked: false,
  },
  {
    id: "iris_ladipo",
    name: "Iris Ladipo",
    householdId: "mystical_besties",
    marked: false,
  },
  {
    id: "flora_ladipo",
    name: "Flora Ladipo",
    householdId: "ladipo",
    marked: false,
  },
  {
    id: "ayo_ladipo",
    name: "Ayo Ladipo",
    householdId: "ladipo",
    marked: false,
  },
  { id: "glen_nhoam", name: "Glen Nhoam", householdId: "nhoam", marked: false },
  {
    id: "todd_attenberry",
    name: "Todd Attenberry",
    householdId: "enchanted_lovers",
    marked: false,
  },
  {
    id: "elric_demuray",
    name: "Elric DeMuray",
    householdId: "enchanted_lovers",
    marked: false,
  },
  {
    id: "titania_summerdream",
    name: "Titania Summerdream",
    householdId: "summerdream",
    marked: false,
  },
  {
    id: "oberon_summerdream",
    name: "Oberon Summerdream",
    householdId: "summerdream",
    marked: false,
  },
  {
    id: "mara_summerdream",
    name: "Mara Summerdream",
    householdId: "summerdream",
    marked: false,
  },
  {
    id: "spruce_almighty",
    name: "Spruce Almighty",
    householdId: "spruce_almighty",
    marked: false,
  },
  {
    id: "mother_nature",
    name: "Mother Nature",
    householdId: "mother_nature",
    marked: false,
  },
  { id: "care_ren", name: "Care Ren", householdId: "care_ren", marked: false },
  {
    id: "zhaleh_amani",
    name: "Zhaleh Amani",
    householdId: "zhaleh_amani",
    marked: false,
  },
  {
    id: "joe_trader",
    name: "Joe Trader",
    householdId: "joe_trader",
    marked: false,
  },
  {
    id: "kim_goldbloom",
    name: "Kim Goldbloom",
    householdId: "goldbloom",
    marked: false,
  },
  {
    id: "michael_bell",
    name: "Michael Bell",
    householdId: "bell",
    marked: false,
  },
];
