import { World } from "@/types";

export const worlds: World[] = [
  {
    order: "01",
    id: "willow_creek",
    name: "Willow Creek",
    pack: "bg",
    type: "residential",
  },
  {
    order: "02",
    id: "oasis_springs",
    name: "Oasis Springs",
    pack: "bg",
    type: "residential",
  },
  {
    order: "00",
    id: "newcrest",
    name: "Newcrest",
    pack: "bg",
    type: "empty",
  },
  {
    order: "00",
    id: "magnolia_promenade",
    name: "Magnolia Promenade",
    pack: "gp01",
    type: "empty",
  },
  {
    order: "00",
    id: "granite_falls",
    name: "Granite Falls",
    pack: "gp01",
    type: "vacation",
  },
  {
    order: "00",
    id: "selvadorada",
    name: "Selvadorada",
    pack: "gp06",
    type: "vacation",
  },
  {
    order: "00",
    id: "batuu",
    name: "Batuu",
    pack: "gp09",
    type: "vacation",
  },
  {
    order: "03",
    id: "windenburg",
    name: "Windenburg",
    pack: "ep02",
    type: "residential",
  },
  {
    order: "04",
    id: "san_myshuno",
    name: "San Myshuno",
    pack: "ep03",
    type: "residential",
  },
  {
    order: "05",
    id: "forgotten_hollow",
    name: "Forgotten Hollow",
    pack: "gp04",
    type: "residential",
  },
  {
    order: "06",
    id: "brindleton_bay",
    name: "Brindleton Bay",
    pack: "ep04",
    type: "residential",
  },
  {
    order: "07",
    id: "del_sol_valley",
    name: "Del Sol Valley",
    pack: "ep06",
    type: "residential",
  },
  {
    order: "08",
    id: "strangerville",
    name: "StrangerVille",
    pack: "gp07",
    type: "residential",
  },
  {
    order: "09",
    id: "sulani",
    name: "Sulani",
    pack: "ep07",
    type: "residential",
  },
  {
    order: "10",
    id: "britechester",
    name: "Britechester",
    pack: "ep08",
    type: "residential",
  },
  {
    order: "11",
    id: "evergreen_harbor",
    name: "Evergreen Harbor",
    pack: "ep09",
    type: "residential",
  },
  {
    order: "12",
    id: "mt_komorebi",
    name: "Mt. Komorebi",
    pack: "ep10",
    type: "residential",
  },
  {
    order: "13",
    id: "henford_on_bagley",
    name: "Henford-on-Bagley",
    pack: "ep11",
    type: "residential",
  },
  {
    order: "14",
    id: "tartosa",
    name: "Tartosa",
    pack: "gp11",
    type: "residential",
  },
  {
    order: "15",
    id: "moonwood_mill",
    name: "Moonwood Mill",
    pack: "gp12",
    type: "residential",
  },
  {
    order: "16",
    id: "copperdale",
    name: "Copperdale",
    pack: "ep12",
    type: "residential",
  },
  {
    order: "17",
    id: "san_sequoia",
    name: "San Sequoia",
    pack: "ep13",
    type: "residential",
  },
  {
    order: "18",
    id: "chestnut_ridge",
    name: "Chestnut Ridge",
    pack: "ep14",
    type: "residential",
  },
  {
    order: "19",
    id: "tomarang",
    name: "Tomarang",
    pack: "ep15",
    type: "residential",
  },
  {
    order: "20",
    id: "ciudad_enamorada",
    name: "Ciudad Enamorada",
    pack: "gp13",
    type: "residential",
  },
  {
    order: "21",
    id: "ravenwood",
    name: "Ravenwood",
    pack: "gp14",
    type: "residential",
  },
  {
    order: "22",
    id: "nordhaven",
    name: "Nordhaven",
    pack: "ep15",
    type: "residential",
  },
  {
    order: "23",
    id: "innisgreen",
    name: "Innisgreen",
    pack: "ep15",
    type: "residential",
  },
];
